<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="7" passed="3" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-31T15:55:02 IST" name="Suite" finished-at="2024-08-31T15:55:34 IST" duration-ms="31145">
    <groups>
      <group name="Error Validation">
        <method signature="ErrorValidation.ErrorValidationOnUserName()[pri:0, instance:SeleniumTestingSubeka.ECommerceE2E.ErrorValidation@6187d1f5]" name="ErrorValidationOnUserName" class="SeleniumTestingSubeka.ECommerceE2E.ErrorValidation"/>
      </group> <!-- Error Validation -->
      <group name="End end Testing">
        <method signature="FirstTest.ECommerceTesting(java.util.HashMap)[pri:0, instance:SeleniumTestingSubeka.ECommerceE2E.FirstTest@29a0cdb]" name="ECommerceTesting" class="SeleniumTestingSubeka.ECommerceE2E.FirstTest"/>
      </group> <!-- End end Testing -->
    </groups>
    <test started-at="2024-08-31T15:55:02 IST" name="Error Validation" finished-at="2024-08-31T15:55:25 IST" duration-ms="22636">
      <class name="SeleniumTestingSubeka.ECommerceE2E.ErrorValidation">
        <test-method is-config="true" signature="launchTheApp()[pri:0, instance:SeleniumTestingSubeka.ECommerceE2E.ErrorValidation@6187d1f5]" started-at="2024-08-31T15:55:02 IST" name="launchTheApp" finished-at="2024-08-31T15:55:07 IST" duration-ms="4220" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchTheApp -->
        <test-method retried="true" signature="ErrorValidationOnUserName()[pri:0, instance:SeleniumTestingSubeka.ECommerceE2E.ErrorValidation@6187d1f5]" started-at="2024-08-31T15:55:07 IST" name="ErrorValidationOnUserName" finished-at="2024-08-31T15:55:08 IST" duration-ms="1172" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrt email or password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrt email or password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at SeleniumTestingSubeka.ECommerceE2E.ErrorValidation.ErrorValidationOnUserName(ErrorValidation.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ErrorValidationOnUserName -->
        <test-method is-config="true" signature="close()[pri:0, instance:SeleniumTestingSubeka.ECommerceE2E.ErrorValidation@6187d1f5]" started-at="2024-08-31T15:55:08 IST" name="close" finished-at="2024-08-31T15:55:08 IST" duration-ms="157" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method is-config="true" signature="launchTheApp()[pri:0, instance:SeleniumTestingSubeka.ECommerceE2E.ErrorValidation@6187d1f5]" started-at="2024-08-31T15:55:08 IST" name="launchTheApp" finished-at="2024-08-31T15:55:11 IST" duration-ms="2962" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchTheApp -->
        <test-method signature="ErrorValidationOnUserName()[pri:0, instance:SeleniumTestingSubeka.ECommerceE2E.ErrorValidation@6187d1f5]" started-at="2024-08-31T15:55:11 IST" name="ErrorValidationOnUserName" finished-at="2024-08-31T15:55:12 IST" duration-ms="1137" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrt email or password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrt email or password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at SeleniumTestingSubeka.ECommerceE2E.ErrorValidation.ErrorValidationOnUserName(ErrorValidation.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ErrorValidationOnUserName -->
        <test-method is-config="true" signature="close()[pri:0, instance:SeleniumTestingSubeka.ECommerceE2E.ErrorValidation@6187d1f5]" started-at="2024-08-31T15:55:13 IST" name="close" finished-at="2024-08-31T15:55:13 IST" duration-ms="102" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method is-config="true" signature="launchTheApp()[pri:0, instance:SeleniumTestingSubeka.ECommerceE2E.ErrorValidation@6187d1f5]" started-at="2024-08-31T15:55:13 IST" name="launchTheApp" finished-at="2024-08-31T15:55:14 IST" duration-ms="1228" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchTheApp -->
        <test-method signature="productErrorValidation()[pri:0, instance:SeleniumTestingSubeka.ECommerceE2E.ErrorValidation@6187d1f5]" started-at="2024-08-31T15:55:14 IST" name="productErrorValidation" finished-at="2024-08-31T15:55:25 IST" duration-ms="10756" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at SeleniumTestingSubeka.ECommerceE2E.ErrorValidation.productErrorValidation(ErrorValidation.java:39)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productErrorValidation -->
        <test-method is-config="true" signature="close()[pri:0, instance:SeleniumTestingSubeka.ECommerceE2E.ErrorValidation@6187d1f5]" started-at="2024-08-31T15:55:25 IST" name="close" finished-at="2024-08-31T15:55:25 IST" duration-ms="127" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- SeleniumTestingSubeka.ECommerceE2E.ErrorValidation -->
    </test> <!-- Error Validation -->
    <test started-at="2024-08-31T15:55:02 IST" name="E2E Testing" finished-at="2024-08-31T15:55:34 IST" duration-ms="31145">
      <class name="SeleniumTestingSubeka.ECommerceE2E.FirstTest">
        <test-method is-config="true" signature="launchTheApp()[pri:0, instance:SeleniumTestingSubeka.ECommerceE2E.FirstTest@29a0cdb]" started-at="2024-08-31T15:55:03 IST" name="launchTheApp" finished-at="2024-08-31T15:55:07 IST" duration-ms="4277" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchTheApp -->
        <test-method signature="ECommerceTesting(java.util.HashMap)[pri:0, instance:SeleniumTestingSubeka.ECommerceE2E.FirstTest@29a0cdb]" started-at="2024-08-31T15:55:07 IST" name="ECommerceTesting" data-provider="getdata" finished-at="2024-08-31T15:55:17 IST" duration-ms="9788" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{prodName=ZARA COAT 3, password=Chithra@subi8, email=subisubi8@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ECommerceTesting -->
        <test-method is-config="true" signature="close()[pri:0, instance:SeleniumTestingSubeka.ECommerceE2E.FirstTest@29a0cdb]" started-at="2024-08-31T15:55:17 IST" name="close" finished-at="2024-08-31T15:55:17 IST" duration-ms="130" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method is-config="true" signature="launchTheApp()[pri:0, instance:SeleniumTestingSubeka.ECommerceE2E.FirstTest@29a0cdb]" started-at="2024-08-31T15:55:17 IST" name="launchTheApp" finished-at="2024-08-31T15:55:20 IST" duration-ms="3174" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchTheApp -->
        <test-method signature="ECommerceTesting(java.util.HashMap)[pri:0, instance:SeleniumTestingSubeka.ECommerceE2E.FirstTest@29a0cdb]" started-at="2024-08-31T15:55:20 IST" name="ECommerceTesting" data-provider="getdata" finished-at="2024-08-31T15:55:30 IST" duration-ms="9777" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{prodName=ADIDAS ORIGINAL, password=Chithra@subi8, email=subisubishivan8@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ECommerceTesting -->
        <test-method is-config="true" signature="close()[pri:0, instance:SeleniumTestingSubeka.ECommerceE2E.FirstTest@29a0cdb]" started-at="2024-08-31T15:55:30 IST" name="close" finished-at="2024-08-31T15:55:30 IST" duration-ms="110" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method is-config="true" signature="launchTheApp()[pri:0, instance:SeleniumTestingSubeka.ECommerceE2E.FirstTest@29a0cdb]" started-at="2024-08-31T15:55:30 IST" name="launchTheApp" finished-at="2024-08-31T15:55:33 IST" duration-ms="2864" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchTheApp -->
        <test-method signature="orderCheckListValidation()[pri:0, instance:SeleniumTestingSubeka.ECommerceE2E.FirstTest@29a0cdb]" started-at="2024-08-31T15:55:33 IST" name="orderCheckListValidation" finished-at="2024-08-31T15:55:33 IST" depends-on-methods="SeleniumTestingSubeka.ECommerceE2E.FirstTest.ECommerceTesting" duration-ms="695" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderCheckListValidation -->
        <test-method is-config="true" signature="close()[pri:0, instance:SeleniumTestingSubeka.ECommerceE2E.FirstTest@29a0cdb]" started-at="2024-08-31T15:55:33 IST" name="close" finished-at="2024-08-31T15:55:34 IST" duration-ms="96" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- SeleniumTestingSubeka.ECommerceE2E.FirstTest -->
    </test> <!-- E2E Testing -->
  </suite> <!-- Suite -->
</testng-results>
